title: My Blog
author: Muhammed Ahmed Salim
email: xahmed94x@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I talk about myself!

# social links
twitter_username: ahmed_salim_94 # DO NOT include the @ character, or else the build will fail!
github_username:  Ahmed-Salim # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
